import { PromptTemplate } from "https://esm.sh/v118/langchain@0.0.75/prompts";

export const PLANNER_SYSTEM_PROMPT_MESSAGE_TEMPLATE = [
  `You are an agent in the planning phase of the task.`,
].join(" ");

export const PLANNER_WORK_PROMPT = PromptTemplate.fromTemplate([
  `You are an agent in the planning phase of the task.\n`,
  `Given the following task with task ID {step_no}, `,
  `please provide an iterative plan to achieve it:\n`,
  `${"```\n"}{task}${"\n```\n"}`,
  `For reference, these are the parent steps of the task:\n`,
  `${"```\n"}{context}${"\n```\n"}`,
  `If this is a complex task requiring a variety of different actions, `,
  `the plan should break down the task into manageable steps, `,
  `where each step comprises of a few actions that can be `,
  `executed in a short time frame.\n`,
  `A task that requires only few or simple actions or is too similar `,
  `to one of its parent tasks shall not be broken down into steps. `,
  `Please refrain from breaking down tasks when not needed. `,
  `Steps don't need to be atomic, often should not even be.\n`,
  `Provide your response strictly in this YAML format:\n`,
  `${"```\n"}breakdown:\n  - step: <no>\n    title: <title>\n    description: <details>${"\n```\n"}`,
  `\n`,
  `Remember that the agent that will execute the plan `,
  `will have access to the following tools:\n{tools}\n`,
].join(""));

// export const PLANNER_INTEGRATE_PROMPT = PromptTemplate.fromTemplate([
//   `You are an agent in the planning phase of the task.\n`,
//   `\n`,
//   `OBJECTIVE:\n`,
//   `Given the following task with task ID {step_no} and its breakdown into smaller steps, `,
//   `please provide the final breakdown of the task to be integrated into the overall `,
//   `execution plan, strictly according to the response format outlined below (RESPONSE FORMAT).\n`,
//   `Task:`,
//   `${"```\n"}{task}${"\n```\n"}`,
//   `For reference, these are the parent steps of the task and the task itself:\n`,
//   `${"```\n"}{context}${"\n```\n"}`,
//   `In a previous iteration, the agent has already drafted the following breakdown of task into substeps:\n`,
//   `${"```\n"}{breakdown}${"\n```\n"}\n`,
//   `You are allowed to modify the breakdown if the resulting plan does not satisfy the plan rules well.\n`,
//   `\n`,
//   `PLAN RULES:\n`,
//   `If this is a complex task requiring a variety of different actions, `,
//   `the plan should break down the task into manageable steps, `,
//   `where each step comprises of a few actions that can be `,
//   `executed in a short time frame.\n`,
//   `A task that requires only few or simple actions or is too similar `,
//   `to one of its parent tasks shall not be broken down into steps. `,
//   `Please refrain from breaking down tasks when not needed. `,
//   `Steps don't need to be atomic, often should not be.\n`,
//   `\n`,
//   `RESPONSE FORMAT:\n`,
//   `Provide your response in one of the following formats.\n`,
//   `1. Breakdown of the task into steps\n`,
//   `If the task is to be broken down into steps, `,
//   `output each step's description and only its `,
//   `description without any prefixes, each step is a `,
//   `separate line. Do not repeat the task in your response.\n`,
//   `Example:\n`,
//   `${"```\n"}First step description\nSecond step\n...${"\n```\n"}`,
//   `2. Keep task as is, since it can be executed in one step\n`,
//   `If the task is not to be broken down into steps, `,
//   `the task itself should be the only line in your response.\n`,
//   `Example:\n`,
//   `${"```\n"}Original task description${"\n```\n"}`,
//   `\n`,
//   `TOOLS:\n`,
//   `Remember that the agent that will execute the plan `,
//   `will have access to the following tools:\n{tools}\n`,
// ].join(""));

export const STEP_EXECUTOR_WORK_MESSAGE_TEMPLATE = [
  `You are working on step {step_no} of the plan now. Execute the step as described and report the result.`,
  `Step {step_no}:`,
  `{step_task}\n\n`,
  `Other related steps for your reference:`,
  `{step_context}\n\n`,
  `{agent_scratchpad}`,
].join("\n");
